version: '3.4'
services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: INFO
    depends_on:
      - redis

  redis:
    image: "redis:6.2.1-buster"
    restart: "unless-stopped"
    ports:
      - "6379:6379"
